"""empty message

Revision ID: e55ee28da30a
Revises: 
Create Date: 2024-04-08 15:46:06.078818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e55ee28da30a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.alter_column('birth_number',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)
        batch_op.alter_column('birth_date',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('postal_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('municipality',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.alter_column('municipality',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('postal_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('birth_date',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('birth_number',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)

    op.drop_table('appointment')
    # ### end Alembic commands ###
